version: '3.8'

services:
  # create mongoDB
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: unless-stopped #restart pod if falling unless it manualy stoped 
    volumes:
      - mongodbdata:/data/db
    networks:
      - backhand
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_URI: ${MONGODB_URI}
    healthcheck: #check if container is up
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  #create application 
  app:
    build: . #run the dockerfile in this dir
    container_name: demo-crm
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backhand
      - frontend
    environment:
      MONGODB_URI: ${MONGODB_URI}
      RABBITMQ_URI: ${RABBITMQ_URI}
      LOG_LEVEL: ${LOG_LEVEL}
      PERSISTENCE: ${PERSISTENCE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  #create nginx 
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" #expose port 80 of nginx to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - frontend
networks:
  backhand:
  frontend:

volumes:
  mongodbdata:
