name: Demo Crm CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  
        cache: 'yarn'
        
    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build Application
      run: yarn build
      
    - name: Start Application
      run: yarn run dev &
      

    - name: Wait for the app to start
      run: |
        for i in {1..10}; do
          curl http://localhost:3000 && break
          echo "Waiting for app..."
          sleep 2
    
        done
        
  package_and_E2E:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
  
    - name: Package the application
      run: docker build -t demo-crm:latest .
    - name: container delete
      run: docker compose down
    - name: build container with docker compose
      run: docker compose up -d
    - name: Wait for the application to start and mkae E2E test
      run: |
        for i in {1..10}; do
          curl http://localhost:3000 && break
          echo "Waiting for app..."
          sleep 2
        done
    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.ECR_ACCESS_KEY }} && aws configure set aws_secret_access_key ${{ secrets.ECR_SECRET_KEY }} && aws configure set region ap-south-1
    - name: Authenticat Docker to ECR 
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 881490105022.dkr.ecr.ap-south-1.amazonaws.com
    - name: Tag Docker image
      run: docker tag demo-crm:latest 881490105022.dkr.ecr.ap-south-1.amazonaws.com/development/demo-crm:latest
    - name: Push Docker image to ECR
      run: docker push 881490105022.dkr.ecr.ap-south-1.amazonaws.com/development/demo-crm:latest
