name: Demo Crm CI

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  pull_request:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build and test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (or your preferred environment)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust the version as needed

    - name: Install dependencies
      run: npm install  # Adjust this if using a different package manager

    - name: Build the app
      run: npm run build  # Adjust the build command if necessary
      
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (or your preferred environment)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust the version as needed

    - name: Install dependencies
      run: npm install  # Adjust this if using a different package manager

    - name: Run unit tests
      run: npm test  # Adjust the test command if necessary
